TRUNCATE TABLE #PERSON_OPT;
DROP TABLE #PERSON_OPT;

TRUNCATE TABLE #BASE_LINE_COUNTER_C;
DROP TABLE #BASE_LINE_COUNTER_C;

TRUNCATE TABLE #BASE_LINE_COUNTER_CY;
DROP TABLE #BASE_LINE_COUNTER_CY;

TRUNCATE TABLE #BASE_LINE_COUNTER_CX;
DROP TABLE #BASE_LINE_COUNTER_CX;

TRUNCATE TABLE #BASE_LINE_COUNTER_CXY;
DROP TABLE #BASE_LINE_COUNTER_CXY;

TRUNCATE TABLE #concepts_of_interest;
DROP TABLE #concepts_of_interest;

TRUNCATE TABLE #exposure_outcome;
DROP TABLE #exposure_outcome;
