IF OBJECT_ID('PERSON_OPT', 'U') IS NOT NULL 
  DROP TABLE PERSON_OPT;

IF OBJECT_ID('BASE_LINE_COUNTER_C', 'U') IS NOT NULL 
  DROP TABLE BASE_LINE_COUNTER_C;

IF OBJECT_ID('BASE_LINE_COUNTER_CY', 'U') IS NOT NULL 
  DROP TABLE BASE_LINE_COUNTER_CY;

IF OBJECT_ID('BASE_LINE_COUNTER_CX', 'U') IS NOT NULL 
  DROP TABLE BASE_LINE_COUNTER_CX;

IF OBJECT_ID('BASE_LINE_COUNTER_CXY', 'U') IS NOT NULL 
  DROP TABLE BASE_LINE_COUNTER_CXY;

IF OBJECT_ID('concepts_of_interest', 'U') IS NOT NULL 
  DROP TABLE concepts_of_interest;

IF OBJECT_ID('exposure_outcome', 'U') IS NOT NULL 
  DROP TABLE exposure_outcome;
