# This file has been autogenerated. Do not change by hand. 

#' Create a parameter object for the function getDbIctpdData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param controlPeriodStart   start of the control period - can be set between -99999 and 0, default
#'                             is -1080.
#' @param controlPeriodEnd     end of the control period - can be set between -99999 and 0, default is
#'                             -361.
#' @param riskPeriodStart      start of the risk period - can be set between 0 and 99999, default is 1.
#' @param riskPeriodEnd        end of the risk period - can be set between 0 and 99999, default is 30.
#' @param censor               a flag indicating wether the method should censor the observation period
#'                             at the end of exposure or not. Available input is 0 or 1 with default =
#'                             0.
#'
#' @export
createGetDbIctpdDataArgs <- function(controlPeriodStart = -1080,
                                     controlPeriodEnd = -361,
                                     riskPeriodStart = 1,

  riskPeriodEnd = 30, censor = FALSE) {
  analysis <- list()
  for (name in names(formals(createGetDbIctpdDataArgs))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function calculateStatisticsIc
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param multipleControlPeriods   Defines the control periods to use where 100 means the control
#'                                 period defined by controlPeriodStart/End, 010 means the period -30
#'                                 to -1 day before prescription and 001 means the control period on
#'                                 the day of prescription
#' @param multipleRiskPeriods      Defines the risk periods to use 10000 is 1-30 days, 01000 is 1 to
#'                                 360 days, 00100 is 31 to 90 days, 00010 is 91 to 180 and 00001 is
#'                                 721 to 1080 days after prescription default is '10000'
#' @param shrinkage                Shrinkage used in IRR calculations, required >0 to deal with 0 case
#'                                 counts, but larger number means more shrinkage. default is 0.5
#' @param icPercentile             The lower bound of the credibility interval for the IC values
#'                                 (IClow). default is 0.025,
#' @param metric                   Defines wether the output will contain the point estimate or the
#'                                 lower bound. Available input is 'IC and 'IC025' default is 'IC025'
#'
#' @export
createCalculateStatisticsIcArgs <- function(multipleControlPeriods = "110",
                                            multipleRiskPeriods = "10000",

  shrinkage = 0.5, icPercentile = 0.025, metric = "IC025") {
  analysis <- list()
  for (name in names(formals(createCalculateStatisticsIcArgs))) {
    analysis[[name]] <- get(name)
  }
  class(analysis) <- "args"
  return(analysis)
}
