# @file PackageMaintenance
#
# Copyright 2018 Observational Health Data Sciences and Informatics
#
# This file is part of IcTemporalPatternDiscovery
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("IcTemporalPatternDiscovery")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual
shell("rm extras/IcTemporalPatternDiscovery.pdf")
shell("R CMD Rd2pdf ./ --output=extras/IcTemporalPatternDiscovery.pdf")

pkgdown::build_site()


# Create args functions
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- OhdsiRTools::createArgFunction("getDbIctpdData",
                                        excludeArgs = c("connectionDetails",
                                                        "cdmDatabaseSchema",
                                                        "oracleTempSchema",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "outcomeDatabaseSchema",
                                                        "outcomeTable",
                                                        "cdmVersion",
                                                        "exposureOutcomePairs"),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("calculateStatisticsIc",
                                        excludeArgs = c("ictpdData"),
                                        rCode = rCode)
writeLines(rCode, "r/CreateArgFunctions.R")
OhdsiRTools::formatRFile("r/CreateArgFunctions.R")
